package main_regresion_polinomial;

import javax.swing.JOptionPane;

/**
 *
 * @author vladi
 */
public class frmlrRegre_polinomial2 extends javax.swing.JFrame {
    double trans1,trans2,trans3,trans4,trans5,trans6,trans7,trans8,trans9;
    double adjT1,adjT2,adjT3,adjT4,adjT5,adjT6,adjT7,adjT8,adjT9;
    double div;
    double mDiv1,mDiv2,mDiv3,mDiv4,mDiv5,mDiv6,mDiv7,mDiv8,mDiv9;
    double cs2,cs4,cs6,cs8;//variables que guardan "n" numero y le cambia de signo 
                          //(si es positivo lo cambia a negativo o viceversa)
    int n = 7;
    
    /**
     * Creates new form Invesrsa_de_una_Matriz
     */
    public frmlrRegre_polinomial2() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        lbR1.setText("");
        lbR2.setText("");
        lbR3.setText("");
        lbR4.setText("");
        lbR5.setText("");
        lbR6.setText("");
        lbR7.setText("");
        lbR8.setText("");
        lbR9.setText("");
    }
    
    //redondear a dos decimales
     private Double redo(Double N){
        return (Math.rint(N*100)/100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCamp2 = new javax.swing.JTextField();
        txtCamp3 = new javax.swing.JTextField();
        txtCamp4 = new javax.swing.JTextField();
        txtCamp1 = new javax.swing.JTextField();
        txtCamp5 = new javax.swing.JTextField();
        txtCamp6 = new javax.swing.JTextField();
        txtCamp7 = new javax.swing.JTextField();
        txtCamp8 = new javax.swing.JTextField();
        txtCamp9 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbR2 = new javax.swing.JLabel();
        lbR3 = new javax.swing.JLabel();
        lbR4 = new javax.swing.JLabel();
        lbR1 = new javax.swing.JLabel();
        lbR5 = new javax.swing.JLabel();
        lbR6 = new javax.swing.JLabel();
        lbR8 = new javax.swing.JLabel();
        lbR9 = new javax.swing.JLabel();
        lbR7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtConst2 = new javax.swing.JTextField();
        txtConst3 = new javax.swing.JTextField();
        txtConst1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txt_x = new javax.swing.JTextField();
        txt_y = new javax.swing.JTextField();
        txt_z = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lbResultado_polinomial = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtX1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtX2 = new javax.swing.JTextField();
        txtX3 = new javax.swing.JTextField();
        txtX4 = new javax.swing.JTextField();
        txtX6 = new javax.swing.JTextField();
        txtX7 = new javax.swing.JTextField();
        txtX5 = new javax.swing.JTextField();
        txtY1 = new javax.swing.JTextField();
        txtY2 = new javax.swing.JTextField();
        txtY3 = new javax.swing.JTextField();
        txtY4 = new javax.swing.JTextField();
        txtY5 = new javax.swing.JTextField();
        txtY6 = new javax.swing.JTextField();
        txtY7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        txtCamp2.setEditable(false);
        txtCamp2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCamp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp2ActionPerformed(evt);
            }
        });

        txtCamp3.setEditable(false);
        txtCamp3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCamp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp3ActionPerformed(evt);
            }
        });

        txtCamp4.setEditable(false);
        txtCamp4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCamp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp4ActionPerformed(evt);
            }
        });

        txtCamp1.setEditable(false);
        txtCamp1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCamp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp1ActionPerformed(evt);
            }
        });

        txtCamp5.setEditable(false);
        txtCamp5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCamp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp5ActionPerformed(evt);
            }
        });

        txtCamp6.setEditable(false);
        txtCamp6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCamp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp6ActionPerformed(evt);
            }
        });

        txtCamp7.setEditable(false);
        txtCamp7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCamp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp7ActionPerformed(evt);
            }
        });

        txtCamp8.setEditable(false);
        txtCamp8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCamp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp8ActionPerformed(evt);
            }
        });

        txtCamp9.setEditable(false);
        txtCamp9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCamp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCamp7, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(txtCamp4)
                    .addComponent(txtCamp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCamp2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCamp5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(txtCamp8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCamp6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCamp3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCamp5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCamp7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        lbR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbR2.setText("Resultado");

        lbR3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbR3.setText("Resultado");

        lbR4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbR4.setText("Resultado");

        lbR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbR1.setText("Resultado");

        lbR5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbR5.setText("Resultado");

        lbR6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbR6.setText("Resultado");

        lbR8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbR8.setText("Resultado");

        lbR9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbR9.setText("Resultado");

        lbR7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbR7.setText("Resultado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbR4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbR8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbR5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbR2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbR3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbR2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbR4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbR8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText("Matriz");

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setText("Resultado de la matriz inversa: ");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("REGRESIÓN POLINOMIAL GRADO2");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtConst2.setEditable(false);
        txtConst2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtConst3.setEditable(false);
        txtConst3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtConst1.setEditable(false);
        txtConst1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtConst1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtConst3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConst2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(txtConst1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(txtConst2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(txtConst3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Determinate:");

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_x.setEditable(false);
        txt_x.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_x.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_xActionPerformed(evt);
            }
        });

        txt_y.setEditable(false);
        txt_y.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_y.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_yActionPerformed(evt);
            }
        });

        txt_z.setEditable(false);
        txt_z.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_z.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_zActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Resultado");

        lbResultado_polinomial.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbResultado_polinomial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(txt_x, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_y, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_z, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)
                        .addComponent(lbResultado_polinomial, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_x, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_y, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_z, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbResultado_polinomial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        txtX1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("        X");

        txtX2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtX3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtX4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtX6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtX7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtX5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtY1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtY2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtY3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtY4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtY5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtY6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtY7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("        Y");

        jButton3.setBackground(new java.awt.Color(204, 102, 255));
        jButton3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton3.setText("Llenar matriz");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtX3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtX4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtX5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtX6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtX7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtY1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtY2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtY3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtY4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtY5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtY6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtY7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtY3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtY4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtY5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtY6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtY7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtY1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtY2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtX3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtX4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtX5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtX6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtX7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_regresion_polinomial/formula regresion polimonial.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese los datos de X y Y ");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("  =");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText("  =");

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setText("  =");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(49, 49, 49)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(459, 459, 459))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(412, 412, 412)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)))
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCamp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp2ActionPerformed

    private void txtCamp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp3ActionPerformed

    private void txtCamp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp4ActionPerformed

    private void txtCamp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp1ActionPerformed

    private void txtCamp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp5ActionPerformed

    private void txtCamp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp6ActionPerformed

    private void txtCamp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp7ActionPerformed

    private void txtCamp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp8ActionPerformed

    private void txtCamp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            //variables de posicion en la matriz
            double posic1=Double.parseDouble(txtCamp1.getText());
            double posic2=Double.parseDouble(txtCamp2.getText());
            double posic3=Double.parseDouble(txtCamp3.getText());
            double posic4=Double.parseDouble(txtCamp4.getText());
            double posic5=Double.parseDouble(txtCamp5.getText());
            double posic6=Double.parseDouble(txtCamp6.getText());
            double posic7=Double.parseDouble(txtCamp7.getText());
            double posic8=Double.parseDouble(txtCamp8.getText());
            double posic9=Double.parseDouble(txtCamp9.getText());
            

            

            //Determinate por el metodo de Sarrus
            double p1 = posic1*posic5*posic9;
            double p2 = posic4*posic8*posic3;
            double p3 = posic7*posic2*posic6;
            
            double resultado1 = p1+p2+p3;
            
            double n1 = posic3*posic5*posic7;
            double n2 = posic6*posic8*posic1;
            double n3 = posic9*posic2*posic4;
            
            double resultado2 = n1+n2+n3;
            double determinante = resultado1-resultado2;
            jTextField1.setText(""+redo(determinante));
            
            //REGLA CRAMER
            double constante1=Double.parseDouble(txtConst1.getText());
            double constante2=Double.parseDouble(txtConst2.getText());
            double constante3=Double.parseDouble(txtConst3.getText());
            
            //Encontrar det X
            double x1 =constante1*posic5*posic9;
            double x2 =posic2*posic6*constante3;
            double x3 =posic3*constante2*posic8;
            double resultadoX1 = x1+x2+x3;
            
            double x4 =posic3*posic5*constante3;
            double x5 =constante1*posic6*posic8;
            double x6 =posic2*constante2*posic9;
            double resultadoX2 = x4+x5+x6;
            double determinanteX = (resultadoX1-resultadoX2)/determinante;
            txt_x.setText("a₀= "+redo(determinanteX));
            
            //Encontrar det Y
            double y1 =posic1*constante2*posic9;
            double y2 =posic4*constante3*posic3;
            double y3 =posic7*constante1*posic6;
            double resultadoY1 = y1+y2+y3;
            
            double y4 =posic3*constante2*posic7;
            double y5 =posic6*constante3*posic1;
            double y6 =posic9*constante1*posic4;
            double resultadoY2 = y4+y5+y6;
            double determinanteY = (resultadoY1 - resultadoY2)/determinante;
            txt_y.setText("a₁= "+redo(determinanteY));
          
            //Encontrar det Z
            double z1 =posic1*posic5*constante3;
            double z2 =posic2*constante2*posic7;
            double z3 =constante1*posic4*posic8;
            double resultadoZ1 = z1+z2+z3;
            
            double z4 =constante1*posic5*posic7;
            double z5 =posic1*constante2*posic8;
            double z6 =posic2*posic4*constante3;
            double resultadoZ2 = z4+z5+z6;
            double determinanteZ = (resultadoZ1-resultadoZ2)/determinante;
            txt_z.setText("a₂= "+redo(determinanteZ));
            
    
            //Transpuesta = convertimos filas a columnas
            trans1=posic1;
            trans2=posic4;
            trans3=posic7;
            trans4=posic2;
            trans5=posic5;
            trans6=posic8;
            trans7=posic3;
            trans8=posic6;
            trans9=posic9;
            
            //Adjunta
            adjT1=(trans5*trans9)-(trans6*trans8);
            adjT2=(trans4*trans9)-(trans6*trans7);
            adjT3=(trans4*trans8)-(trans5*trans7);
            adjT4=(trans2*trans9)-(trans3*trans8);
            adjT5=(trans1*trans9)-(trans3*trans7);
            adjT6=(trans1*trans8)-(trans2*trans7);
            adjT7=(trans2*trans6)-(trans3*trans5);
            adjT8=(trans1*trans6)-(trans3*trans4);
            adjT9=(trans1*trans5)-(trans2*trans4);
            
            //inversa
            
            div=1/determinante;
            
            mDiv1=div*adjT1;
            mDiv2=div*adjT2;
            mDiv3=div*adjT3;
            mDiv4=div*adjT4;
            mDiv5=div*adjT5;
            mDiv6=div*adjT6;
            mDiv7=div*adjT7;
            mDiv8=div*adjT8;
            mDiv9=div*adjT9;
            //multiplicacion para el cambio de signo
            cs2=mDiv2*-1;
            cs4=mDiv4*-1;
            cs6=mDiv6*-1;
            cs8=mDiv8*-1;
            
            lbR1.setText(""+redo(mDiv1));
            lbR2.setText(""+redo(cs2));//cambia de signo
            lbR3.setText(""+redo(mDiv3));
            lbR4.setText(""+redo(cs4));//cambia de signo
            lbR5.setText(""+redo(mDiv5));
            lbR6.setText(""+redo(cs6));//cambia de signo
            lbR7.setText(""+redo(mDiv7));
            lbR8.setText(""+redo(cs8));//cambia de signo
            lbR9.setText(""+redo(mDiv9));
            
            //Resultado de regresion polinomial
            lbResultado_polinomial.setText("y= "+redo(determinanteZ)+"x²"+" + "+redo(determinanteY)+"x"+" + "+redo(determinanteX));
            
            
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al encontrar los determinates e inversa, revise que los campos esten llenos (matriz y constantes)");
            lbR1.setText("");
            lbR2.setText("");
            lbR3.setText("");
            lbR4.setText("");
            lbR5.setText("");
            lbR6.setText("");
            lbR7.setText("");
            lbR8.setText("");
            lbR9.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(this,"¿Seguro que desea salir?")>0) {
            return;
        }
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_yActionPerformed

    private void txt_zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_zActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_zActionPerformed

    private void txt_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_xActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            //variables de posicion Xn
            double pX1=Double.parseDouble(txtX1.getText());
            double pX2=Double.parseDouble(txtX2.getText());
            double pX3=Double.parseDouble(txtX3.getText());
            double pX4=Double.parseDouble(txtX4.getText());
            double pX5=Double.parseDouble(txtX5.getText());
            double pX6=Double.parseDouble(txtX6.getText());
            double pX7=Double.parseDouble(txtX7.getText());
            
            //variables de posicion Xn
            double pY1=Double.parseDouble(txtY1.getText());
            double pY2=Double.parseDouble(txtY2.getText());
            double pY3=Double.parseDouble(txtY3.getText());
            double pY4=Double.parseDouble(txtY4.getText());
            double pY5=Double.parseDouble(txtY5.getText());
            double pY6=Double.parseDouble(txtY6.getText());
            double pY7=Double.parseDouble(txtY7.getText());
            
            //REGRESION POLIMONIAL GRADO 2
            double sumatoriaX = pX1+pX2+pX3+pX4+pX5+pX6+pX7;
            double Xcuadrado = ((pX1*pX1)+(pX2*pX2)+(pX3*pX3)+(pX4*pX4)+(pX5*pX5)+(pX6*pX6)+(pX7*pX7));
            double sumatoriaY = pY1+pY2+pY3+pY4+pY5+pY6+pY7;
            double Xcubo= ((pX1*pX1*pX1)+(pX2*pX2*pX2)+(pX3*pX3*pX3)+(pX4*pX4*pX4)+(pX5*pX5*pX5)+(pX6*pX6*pX6)+(pX7*pX7*pX7));
            double Xcuarta= ((pX1*pX1*pX1*pX1)+(pX2*pX2*pX2*pX2)+(pX3*pX3*pX3*pX3)+(pX4*pX4*pX4*pX4)+(pX5*pX5*pX5*pX5)+(pX6*pX6*pX6*pX6)+(pX7*pX7*pX7*pX7));
            double sumatoriaX_Y = ((pX1*pY1)+(pX2*pY2)+(pX3*pY3)+(pX4*pY4)+(pX5*pY5)+(pX6*pY6)+(pX7*pY7));
            double SumatoriaX2_Y = ((pX1*pX1*pY1)+(pX2*pX2*pY2)+(pX3*pX3*pY3)+(pX4*pX4*pY4)+(pX5*pX5*pY5)+(pX6*pX6*pY6)+(pX7*pX7*pY7));
            txtCamp1.setText(""+(n));
            txtCamp2.setText(""+redo(sumatoriaX));
            txtCamp3.setText(""+redo(Xcuadrado));
            txtCamp4.setText(""+redo(sumatoriaX));
            txtCamp5.setText(""+redo(Xcuadrado));
            txtCamp6.setText(""+redo(Xcubo));
            txtCamp7.setText(""+redo(Xcuadrado));
            txtCamp8.setText(""+redo(Xcubo));
            txtCamp9.setText(""+redo(Xcuarta));
            txtConst1.setText(""+redo(sumatoriaY));
            txtConst2.setText(""+redo(sumatoriaX_Y));
            txtConst3.setText(""+redo(SumatoriaX2_Y));
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Error al llenar la matriz por favor verifique que todos los datos se hayan sido ingresados");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmlrRegre_polinomial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmlrRegre_polinomial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmlrRegre_polinomial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmlrRegre_polinomial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmlrRegre_polinomial2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbR1;
    private javax.swing.JLabel lbR2;
    private javax.swing.JLabel lbR3;
    private javax.swing.JLabel lbR4;
    private javax.swing.JLabel lbR5;
    private javax.swing.JLabel lbR6;
    private javax.swing.JLabel lbR7;
    private javax.swing.JLabel lbR8;
    private javax.swing.JLabel lbR9;
    private javax.swing.JLabel lbResultado_polinomial;
    private javax.swing.JTextField txtCamp1;
    private javax.swing.JTextField txtCamp2;
    private javax.swing.JTextField txtCamp3;
    private javax.swing.JTextField txtCamp4;
    private javax.swing.JTextField txtCamp5;
    private javax.swing.JTextField txtCamp6;
    private javax.swing.JTextField txtCamp7;
    private javax.swing.JTextField txtCamp8;
    private javax.swing.JTextField txtCamp9;
    private javax.swing.JTextField txtConst1;
    private javax.swing.JTextField txtConst2;
    private javax.swing.JTextField txtConst3;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX2;
    private javax.swing.JTextField txtX3;
    private javax.swing.JTextField txtX4;
    private javax.swing.JTextField txtX5;
    private javax.swing.JTextField txtX6;
    private javax.swing.JTextField txtX7;
    private javax.swing.JTextField txtY1;
    private javax.swing.JTextField txtY2;
    private javax.swing.JTextField txtY3;
    private javax.swing.JTextField txtY4;
    private javax.swing.JTextField txtY5;
    private javax.swing.JTextField txtY6;
    private javax.swing.JTextField txtY7;
    private javax.swing.JTextField txt_x;
    private javax.swing.JTextField txt_y;
    private javax.swing.JTextField txt_z;
    // End of variables declaration//GEN-END:variables
}
